import React, { useState } from 'react';
import { KeyRound, Copy, Check, Eye, EyeOff } from 'lucide-react';

export const UniversityCredentialsCard = ({
  universityName = '',
  loginEmail = '',
  loginPassword = ''
}) => {
  const [showPassword, setShowPassword] = useState(false);
  const [copiedField, setCopiedField] = useState(null);

  const handleCopy = (text, field) => {
    navigator.clipboard.writeText(text);
    setCopiedField(field);
    setTimeout(() => setCopiedField(null), 2000);
  };

  return (
    <div className="bg-white rounded-lg border border-slate-200/90 p-4 sm:p-5 shadow-2xs space-y-3.5 select-none">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 pb-2 border-b border-slate-100">
        <div className="flex items-center space-x-2">
          <KeyRound className="w-3.5 h-3.5 text-blue-600" />
          <div>
            <h3 className="text-xs font-bold uppercase tracking-wider text-slate-900">Official HEI Login Credentials</h3>
            <p className="text-[10px] text-slate-400 font-medium">Generated by Government Admin for University Portal Login</p>
          </div>
        </div>

        <button
          type="button"
          onClick={() => {
            const creds = `University: ${universityName}\nLogin ID: ${loginEmail}\nPassword: ${loginPassword}\nPortal Link: ${window.location.origin}/login`;
            handleCopy(creds, 'all');
          }}
          className="px-3 py-1.5 bg-slate-50 hover:bg-slate-100 text-slate-700 border border-slate-200 rounded-md text-xs font-medium transition-colors cursor-pointer flex items-center space-x-1.5 self-start sm:self-auto shadow-2xs"
        >
          {copiedField === 'all' ? (
            <>
              <Check className="w-3.5 h-3.5 text-emerald-600" />
              <span className="text-emerald-700 font-semibold">Copied to Clipboard!</span>
            </>
          ) : (
            <>
              <Copy className="w-3.5 h-3.5 text-slate-500" />
              <span>Copy Credentials</span>
            </>
          )}
        </button>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
        {/* Login Email */}
        <div className="bg-slate-50/60 rounded-md p-3 border border-slate-200/80 flex items-center justify-between">
          <div>
            <span className="text-[10px] text-slate-400 font-bold uppercase tracking-wider block mb-0.5">Portal Login Email</span>
            <span className="text-xs font-bold text-slate-900 select-all font-mono">{loginEmail}</span>
          </div>
          <button
            type="button"
            onClick={() => handleCopy(loginEmail, 'email')}
            className="p-1 text-slate-400 hover:text-slate-900 hover:bg-slate-100 rounded transition-colors cursor-pointer"
            title="Copy Email"
          >
            {copiedField === 'email' ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5 text-slate-400" />}
          </button>
        </div>

        {/* Generated Password */}
        <div className="bg-slate-50/60 rounded-md p-3 border border-slate-200/80 flex items-center justify-between">
          <div>
            <span className="text-[10px] text-slate-400 font-bold uppercase tracking-wider block mb-0.5">Account Password</span>
            <span className="text-xs font-mono font-bold text-slate-900 select-all">
              {showPassword ? loginPassword : '••••••••••••'}
            </span>
          </div>
          <div className="flex items-center space-x-1">
            <button
              type="button"
              onClick={() => setShowPassword(!showPassword)}
              className="p-1 text-slate-400 hover:text-slate-700 rounded transition-colors cursor-pointer"
              title={showPassword ? 'Hide' : 'Show'}
            >
              {showPassword ? <EyeOff className="w-3.5 h-3.5" /> : <Eye className="w-3.5 h-3.5" />}
            </button>
            <button
              type="button"
              onClick={() => handleCopy(loginPassword, 'password')}
              className="p-1 text-slate-400 hover:text-slate-900 hover:bg-slate-100 rounded transition-colors cursor-pointer"
              title="Copy Password"
            >
              {copiedField === 'password' ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5 text-slate-400" />}
            </button>
          </div>
        </div>
      </div>

      <div className="text-[11px] text-slate-400">
        Representative university staff can use these credentials to log in at <strong className="text-slate-600">/login</strong>.
      </div>
    </div>
  );
};

export default UniversityCredentialsCard;
