export { CSRGrantsLifecycleDashboard } from './CSRGrantsLifecycleDashboard.jsx';
export { CSRPhaseTabs } from './CSRPhaseTabs.jsx';
export { CSRFundingSources } from './CSRFundingSources.jsx';
export { CSRStatutoryParameters } from './CSRStatutoryParameters.jsx';
export { CSRProposalPipelineTable } from './CSRProposalPipelineTable.jsx';
export { CSREscrowMatrix } from './CSREscrowMatrix.jsx';
export { CSRPaymentLedgerTable } from './CSRPaymentLedgerTable.jsx';
export { CSRFundUtilization } from './CSRFundUtilization.jsx';
export { CSRComplianceChecklist } from './CSRComplianceChecklist.jsx';
export { CSRClosureReporting } from './CSRClosureReporting.jsx';
export { CSRDisbursalModesTable } from './CSRDisbursalModesTable.jsx';
export { AddProposalModal } from './AddProposalModal.jsx';
export { ProposalDetailModal } from './ProposalDetailModal.jsx';
export { PaymentDetailModal } from './PaymentDetailModal.jsx';
export { InitiateDisbursalModal } from './InitiateDisbursalModal.jsx';
export { EscrowVaultsModal } from './EscrowVaultsModal.jsx';
export { TdsComplianceModal } from './TdsComplianceModal.jsx';
export { GeoVerificationModal } from './GeoVerificationModal.jsx';
export { Gfr12AModal } from './Gfr12AModal.jsx';
export { CaAuditReportModal } from './CaAuditReportModal.jsx';
export { GatewayConfigModal } from './GatewayConfigModal.jsx';
export { UnspentSweepModal } from './UnspentSweepModal.jsx';
export { SourceDetailsModal } from './SourceDetailsModal.jsx';

export default CSRGrantsLifecycleDashboard;
